unzip -o -d ./KIT_mesh/OrangeMarmelade ./KIT_mesh/OrangeMarmelade.zip 
unzip -o -d ./KIT_mesh/BlueSaltCube ./KIT_mesh/BlueSaltCube.zip 
unzip -o -d ./KIT_mesh/YellowSaltCube ./KIT_mesh/YellowSaltCube.zip 
unzip -o -d ./KIT_mesh/FruitTea ./KIT_mesh/FruitTea.zip 
unzip -o -d ./KIT_mesh/GreenSaltCylinder ./KIT_mesh/GreenSaltCylinder.zip 
unzip -o -d ./KIT_mesh/MashedPotatoes ./KIT_mesh/MashedPotatoes.zip 
unzip -o -d ./KIT_mesh/YellowSaltCylinder ./KIT_mesh/YellowSaltCylinder.zip 
unzip -o -d ./KIT_mesh/Rusk ./KIT_mesh/Rusk.zip 
unzip -o -d ./KIT_mesh/Knaeckebrot ./KIT_mesh/Knaeckebrot.zip 
unzip -o -d ./KIT_mesh/Amicelli ./KIT_mesh/Amicelli.zip 
unzip -o -d ./KIT_mesh/HotPot ./KIT_mesh/HotPot.zip 
unzip -o -d ./KIT_mesh/YellowSaltCube2 ./KIT_mesh/YellowSaltCube2.zip 
unzip -o -d ./KIT_mesh/Sauerkraut ./KIT_mesh/Sauerkraut.zip 
unzip -o -d ./KIT_mesh/LivioClassicOil ./KIT_mesh/LivioClassicOil.zip 
unzip -o -d ./KIT_mesh/LivioSunflowerOil ./KIT_mesh/LivioSunflowerOil.zip 
unzip -o -d ./KIT_mesh/DanishHam ./KIT_mesh/DanishHam.zip 
unzip -o -d ./KIT_mesh/TomatoSoup ./KIT_mesh/TomatoSoup.zip 
unzip -o -d ./KIT_mesh/SauerkrautSmall ./KIT_mesh/SauerkrautSmall.zip 
unzip -o -d ./KIT_mesh/HeringTin ./KIT_mesh/HeringTin.zip 
unzip -o -d ./KIT_mesh/RavioliLarge ./KIT_mesh/RavioliLarge.zip 
unzip -o -d ./KIT_mesh/InstantSoup ./KIT_mesh/InstantSoup.zip 
unzip -o -d ./KIT_mesh/Toothpaste ./KIT_mesh/Toothpaste.zip 
unzip -o -d ./KIT_mesh/HotPot2 ./KIT_mesh/HotPot2.zip 
unzip -o -d ./KIT_mesh/KnaeckebrotRye ./KIT_mesh/KnaeckebrotRye.zip 
unzip -o -d ./KIT_mesh/CeylonTea ./KIT_mesh/CeylonTea.zip 
unzip -o -d ./KIT_mesh/Rice ./KIT_mesh/Rice.zip 
unzip -o -d ./KIT_mesh/FennelTea ./KIT_mesh/FennelTea.zip 
unzip -o -d ./KIT_mesh/MuesliBars ./KIT_mesh/MuesliBars.zip 
unzip -o -d ./KIT_mesh/Deodorant ./KIT_mesh/Deodorant.zip 
unzip -o -d ./KIT_mesh/HygieneSpray ./KIT_mesh/HygieneSpray.zip 
unzip -o -d ./KIT_mesh/PowderedSugar ./KIT_mesh/PowderedSugar.zip 
unzip -o -d ./KIT_mesh/CondensedMilk ./KIT_mesh/CondensedMilk.zip 
unzip -o -d ./KIT_mesh/SoftCakeOrange ./KIT_mesh/SoftCakeOrange.zip 
unzip -o -d ./KIT_mesh/CoffeeFilters ./KIT_mesh/CoffeeFilters.zip 
unzip -o -d ./KIT_mesh/PineappleSlices ./KIT_mesh/PineappleSlices.zip 
unzip -o -d ./KIT_mesh/FruitDrink ./KIT_mesh/FruitDrink.zip 
unzip -o -d ./KIT_mesh/InstantIceCoffee ./KIT_mesh/InstantIceCoffee.zip 
unzip -o -d ./KIT_mesh/ChoppedTomatoes ./KIT_mesh/ChoppedTomatoes.zip 
unzip -o -d ./KIT_mesh/MilkDrinkVanilla ./KIT_mesh/MilkDrinkVanilla.zip 
unzip -o -d ./KIT_mesh/WhippedCream ./KIT_mesh/WhippedCream.zip 
unzip -o -d ./KIT_mesh/PotatoeStarch ./KIT_mesh/PotatoeStarch.zip 
unzip -o -d ./KIT_mesh/InstantDumplings ./KIT_mesh/InstantDumplings.zip 
unzip -o -d ./KIT_mesh/ChocolateBars ./KIT_mesh/ChocolateBars.zip 
unzip -o -d ./KIT_mesh/JamSugar ./KIT_mesh/JamSugar.zip 
unzip -o -d ./KIT_mesh/YellowSaltCylinderSmall ./KIT_mesh/YellowSaltCylinderSmall.zip 
unzip -o -d ./KIT_mesh/InstantMousse ./KIT_mesh/InstantMousse.zip 
unzip -o -d ./KIT_mesh/TomatoSauce ./KIT_mesh/TomatoSauce.zip 
unzip -o -d ./KIT_mesh/PowderedSugarMill ./KIT_mesh/PowderedSugarMill.zip 
unzip -o -d ./KIT_mesh/SauceThickener ./KIT_mesh/SauceThickener.zip 
unzip -o -d ./KIT_mesh/CoffeeFilters2 ./KIT_mesh/CoffeeFilters2.zip 
unzip -o -d ./KIT_mesh/ShowerGel ./KIT_mesh/ShowerGel.zip 
unzip -o -d ./KIT_mesh/Margarine ./KIT_mesh/Margarine.zip 
unzip -o -d ./KIT_mesh/MilkRice ./KIT_mesh/MilkRice.zip 
unzip -o -d ./KIT_mesh/Patches ./KIT_mesh/Patches.zip 
unzip -o -d ./KIT_mesh/PotatoeDumplings ./KIT_mesh/PotatoeDumplings.zip 
unzip -o -d ./KIT_mesh/CoughDropsLemon ./KIT_mesh/CoughDropsLemon.zip 
unzip -o -d ./KIT_mesh/CoughDropsHoney ./KIT_mesh/CoughDropsHoney.zip 
unzip -o -d ./KIT_mesh/CoughDropsBerries ./KIT_mesh/CoughDropsBerries.zip 
unzip -o -d ./KIT_mesh/FruitBars ./KIT_mesh/FruitBars.zip 
unzip -o -d ./KIT_mesh/PatchesSensitive ./KIT_mesh/PatchesSensitive.zip 
unzip -o -d ./KIT_mesh/SardinesCan ./KIT_mesh/SardinesCan.zip 
unzip -o -d ./KIT_mesh/DropsOrange ./KIT_mesh/DropsOrange.zip 
unzip -o -d ./KIT_mesh/DropsCherry ./KIT_mesh/DropsCherry.zip 
unzip -o -d ./KIT_mesh/FizzyTablets ./KIT_mesh/FizzyTablets.zip 
unzip -o -d ./KIT_mesh/FizzyTabletsCalcium ./KIT_mesh/FizzyTabletsCalcium.zip 
unzip -o -d ./KIT_mesh/PotatoeSticks ./KIT_mesh/PotatoeSticks.zip 
unzip -o -d ./KIT_mesh/Wafflerolls ./KIT_mesh/Wafflerolls.zip 
unzip -o -d ./KIT_mesh/Shampoo ./KIT_mesh/Shampoo.zip 
unzip -o -d ./KIT_mesh/HamburgerSauce ./KIT_mesh/HamburgerSauce.zip 
unzip -o -d ./KIT_mesh/RuskWholemeal ./KIT_mesh/RuskWholemeal.zip 
unzip -o -d ./KIT_mesh/NutCandy ./KIT_mesh/NutCandy.zip 
unzip -o -d ./KIT_mesh/KoalaCandy ./KIT_mesh/KoalaCandy.zip 
unzip -o -d ./KIT_mesh/ChickenSoup ./KIT_mesh/ChickenSoup.zip 
unzip -o -d ./KIT_mesh/InstantTomatoSoup ./KIT_mesh/InstantTomatoSoup.zip 
unzip -o -d ./KIT_mesh/BroccoliSoup ./KIT_mesh/BroccoliSoup.zip 
unzip -o -d ./KIT_mesh/CoffeeCookies ./KIT_mesh/CoffeeCookies.zip 
unzip -o -d ./KIT_mesh/BakingSoda ./KIT_mesh/BakingSoda.zip 
unzip -o -d ./KIT_mesh/Sweetener ./KIT_mesh/Sweetener.zip 
unzip -o -d ./KIT_mesh/BakingVanilla ./KIT_mesh/BakingVanilla.zip 
unzip -o -d ./KIT_mesh/ChocoIcing ./KIT_mesh/ChocoIcing.zip 
unzip -o -d ./KIT_mesh/CleaningCloths ./KIT_mesh/CleaningCloths.zip 
unzip -o -d ./KIT_mesh/NutellaGo ./KIT_mesh/NutellaGo.zip 
unzip -o -d ./KIT_mesh/StrawberryPorridge ./KIT_mesh/StrawberryPorridge.zip 
unzip -o -d ./KIT_mesh/OrgFruitTea ./KIT_mesh/OrgFruitTea.zip 
unzip -o -d ./KIT_mesh/OrgHerbTea ./KIT_mesh/OrgHerbTea.zip 
unzip -o -d ./KIT_mesh/WhippedCream2 ./KIT_mesh/WhippedCream2.zip 
unzip -o -d ./KIT_mesh/Marjoram ./KIT_mesh/Marjoram.zip 
unzip -o -d ./KIT_mesh/Curry ./KIT_mesh/Curry.zip 
unzip -o -d ./KIT_mesh/Paprika ./KIT_mesh/Paprika.zip 
unzip -o -d ./KIT_mesh/TomatoHerbSauce ./KIT_mesh/TomatoHerbSauce.zip 
unzip -o -d ./KIT_mesh/ChocSticks ./KIT_mesh/ChocSticks.zip 
unzip -o -d ./KIT_mesh/ChocSticks2 ./KIT_mesh/ChocSticks2.zip 
unzip -o -d ./KIT_mesh/Peanuts ./KIT_mesh/Peanuts.zip 
unzip -o -d ./KIT_mesh/Peanuts2 ./KIT_mesh/Peanuts2.zip 
unzip -o -d ./KIT_mesh/InstantSauce2 ./KIT_mesh/InstantSauce2.zip 
unzip -o -d ./KIT_mesh/Peas ./KIT_mesh/Peas.zip 
unzip -o -d ./KIT_mesh/HerbSalt ./KIT_mesh/HerbSalt.zip 
unzip -o -d ./KIT_mesh/SoftCheese ./KIT_mesh/SoftCheese.zip 
unzip -o -d ./KIT_mesh/BathDetergent ./KIT_mesh/BathDetergent.zip 
unzip -o -d ./KIT_mesh/ChocMarshmallows ./KIT_mesh/ChocMarshmallows.zip 
unzip -o -d ./KIT_mesh/CokePlasticLarge ./KIT_mesh/CokePlasticLarge.zip 
unzip -o -d ./KIT_mesh/CokePlasticSmall ./KIT_mesh/CokePlasticSmall.zip 
unzip -o -d ./KIT_mesh/VitalisCereals ./KIT_mesh/VitalisCereals.zip 
unzip -o -d ./KIT_mesh/SmacksCereals ./KIT_mesh/SmacksCereals.zip 
unzip -o -d ./KIT_mesh/Sprudelflasche ./KIT_mesh/Sprudelflasche.zip 
unzip -o -d ./KIT_mesh/Wineglass ./KIT_mesh/Wineglass.zip 
unzip -o -d ./KIT_mesh/Waterglass ./KIT_mesh/Waterglass.zip 
unzip -o -d ./KIT_mesh/SmallGlass ./KIT_mesh/SmallGlass.zip 
unzip -o -d ./KIT_mesh/Glassbowl ./KIT_mesh/Glassbowl.zip 
unzip -o -d ./KIT_mesh/WhiteCup ./KIT_mesh/WhiteCup.zip 
unzip -o -d ./KIT_mesh/Pitcher ./KIT_mesh/Pitcher.zip 
unzip -o -d ./KIT_mesh/Sprayflask ./KIT_mesh/Sprayflask.zip 
unzip -o -d ./KIT_mesh/InstantSauce ./KIT_mesh/InstantSauce.zip 
unzip -o -d ./KIT_mesh/GreenCup ./KIT_mesh/GreenCup.zip 
unzip -o -d ./KIT_mesh/ToyCarYelloq ./KIT_mesh/ToyCarYelloq.zip 
unzip -o -d ./KIT_mesh/FlowerCup ./KIT_mesh/FlowerCup.zip 
unzip -o -d ./KIT_mesh/MelforBottle ./KIT_mesh/MelforBottle.zip 
unzip -o -d ./KIT_mesh/CokePlasticSmallGrasp ./KIT_mesh/CokePlasticSmallGrasp.zip 
unzip -o -d ./KIT_mesh/RedCup ./KIT_mesh/RedCup.zip 
unzip -o -d ./KIT_mesh/CatLying ./KIT_mesh/CatLying.zip 
unzip -o -d ./KIT_mesh/CatSitting ./KIT_mesh/CatSitting.zip 
unzip -o -d ./KIT_mesh/Clown ./KIT_mesh/Clown.zip 
unzip -o -d ./KIT_mesh/Dog ./KIT_mesh/Dog.zip 
unzip -o -d ./KIT_mesh/Dwarf ./KIT_mesh/Dwarf.zip 
unzip -o -d ./KIT_mesh/Fish ./KIT_mesh/Fish.zip 
unzip -o -d ./KIT_mesh/Heart1 ./KIT_mesh/Heart1.zip 
unzip -o -d ./KIT_mesh/LetterP ./KIT_mesh/LetterP.zip 
unzip -o -d ./KIT_mesh/Moon ./KIT_mesh/Moon.zip 
unzip -o -d ./KIT_mesh/Pony ./KIT_mesh/Pony.zip 
unzip -o -d ./KIT_mesh/Seal ./KIT_mesh/Seal.zip 
unzip -o -d ./KIT_mesh/Tortoise ./KIT_mesh/Tortoise.zip 
unzip -o -d ./KIT_mesh/CoffeeBox ./KIT_mesh/CoffeeBox.zip 
unzip -o -d ./KIT_mesh/Cutter ./KIT_mesh/Cutter.zip 
unzip -o -d ./KIT_mesh/Brush ./KIT_mesh/Brush.zip 
unzip -o -d ./KIT_mesh/Flashlight ./KIT_mesh/Flashlight.zip 
unzip -o -d ./KIT_mesh/Phillips ./KIT_mesh/Phillips.zip 
unzip -o -d ./KIT_mesh/Slotted_Screwdriver ./KIT_mesh/Slotted_Screwdriver.zip 
unzip -o -d ./KIT_mesh/Wrench ./KIT_mesh/Wrench.zip 
unzip -o -d ./KIT_mesh/Spraybottle ./KIT_mesh/Spraybottle.zip 
unzip -o -d ./KIT_mesh/Stanley_Lever ./KIT_mesh/Stanley_Lever.zip 
unzip -o -d ./KIT_mesh/Stanley_Extension_Short ./KIT_mesh/Stanley_Extension_Short.zip 
unzip -o -d ./KIT_mesh/Stanley_Extension_Long ./KIT_mesh/Stanley_Extension_Long.zip 
unzip -o -d ./KIT_mesh/Stanley_Extension_Medium ./KIT_mesh/Stanley_Extension_Medium.zip 
unzip -o -d ./KIT_mesh/Stanley_Handle ./KIT_mesh/Stanley_Handle.zip 
unzip -o -d ./KIT_mesh/Pliers ./KIT_mesh/Pliers.zip
cd KIT_mesh
rm -f  rm *.zip
cd ..
