curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/OrangeMarmelade/meshes.zip" -o ./KIT_mesh/OrangeMarmelade.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/BlueSaltCube/meshes.zip" -o ./KIT_mesh/BlueSaltCube.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/YellowSaltCube/meshes.zip" -o ./KIT_mesh/YellowSaltCube.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/FruitTea/meshes.zip" -o ./KIT_mesh/FruitTea.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/GreenSaltCylinder/meshes.zip" -o ./KIT_mesh/GreenSaltCylinder.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/MashedPotatoes/meshes.zip" -o ./KIT_mesh/MashedPotatoes.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/YellowSaltCylinder/meshes.zip" -o ./KIT_mesh/YellowSaltCylinder.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Rusk/meshes.zip" -o ./KIT_mesh/Rusk.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Knaeckebrot/meshes.zip" -o ./KIT_mesh/Knaeckebrot.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Amicelli/meshes.zip" -o ./KIT_mesh/Amicelli.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/HotPot/meshes.zip" -o ./KIT_mesh/HotPot.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/YellowSaltCube2/meshes.zip" -o ./KIT_mesh/YellowSaltCube2.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Sauerkraut/meshes.zip" -o ./KIT_mesh/Sauerkraut.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/LivioClassicOil/meshes.zip" -o ./KIT_mesh/LivioClassicOil.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/LivioSunflowerOil/meshes.zip" -o ./KIT_mesh/LivioSunflowerOil.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/DanishHam/meshes.zip" -o ./KIT_mesh/DanishHam.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/TomatoSoup/meshes.zip" -o ./KIT_mesh/TomatoSoup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/SauerkrautSmall/meshes.zip" -o ./KIT_mesh/SauerkrautSmall.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/HeringTin/meshes.zip" -o ./KIT_mesh/HeringTin.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/RavioliLarge/meshes.zip" -o ./KIT_mesh/RavioliLarge.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/InstantSoup/meshes.zip" -o ./KIT_mesh/InstantSoup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Toothpaste/meshes.zip" -o ./KIT_mesh/Toothpaste.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/HotPot2/meshes.zip" -o ./KIT_mesh/HotPot2.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/KnaeckebrotRye/meshes.zip" -o ./KIT_mesh/KnaeckebrotRye.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CeylonTea/meshes.zip" -o ./KIT_mesh/CeylonTea.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Rice/meshes.zip" -o ./KIT_mesh/Rice.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/FennelTea/meshes.zip" -o ./KIT_mesh/FennelTea.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/MuesliBars/meshes.zip" -o ./KIT_mesh/MuesliBars.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Deodorant/meshes.zip" -o ./KIT_mesh/Deodorant.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/HygieneSpray/meshes.zip" -o ./KIT_mesh/HygieneSpray.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/PowderedSugar/meshes.zip" -o ./KIT_mesh/PowderedSugar.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CondensedMilk/meshes.zip" -o ./KIT_mesh/CondensedMilk.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/SoftCakeOrange/meshes.zip" -o ./KIT_mesh/SoftCakeOrange.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CoffeeFilters/meshes.zip" -o ./KIT_mesh/CoffeeFilters.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/PineappleSlices/meshes.zip" -o ./KIT_mesh/PineappleSlices.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/FruitDrink/meshes.zip" -o ./KIT_mesh/FruitDrink.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/InstantIceCoffee/meshes.zip" -o ./KIT_mesh/InstantIceCoffee.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ChoppedTomatoes/meshes.zip" -o ./KIT_mesh/ChoppedTomatoes.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/MilkDrinkVanilla/meshes.zip" -o ./KIT_mesh/MilkDrinkVanilla.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/WhippedCream/meshes.zip" -o ./KIT_mesh/WhippedCream.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/PotatoeStarch/meshes.zip" -o ./KIT_mesh/PotatoeStarch.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/InstantDumplings/meshes.zip" -o ./KIT_mesh/InstantDumplings.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ChocolateBars/meshes.zip" -o ./KIT_mesh/ChocolateBars.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/JamSugar/meshes.zip" -o ./KIT_mesh/JamSugar.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/YellowSaltCylinderSmall/meshes.zip" -o ./KIT_mesh/YellowSaltCylinderSmall.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/InstantMousse/meshes.zip" -o ./KIT_mesh/InstantMousse.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/TomatoSauce/meshes.zip" -o ./KIT_mesh/TomatoSauce.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/PowderedSugarMill/meshes.zip" -o ./KIT_mesh/PowderedSugarMill.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/SauceThickener/meshes.zip" -o ./KIT_mesh/SauceThickener.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CoffeeFilters2/meshes.zip" -o ./KIT_mesh/CoffeeFilters2.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ShowerGel/meshes.zip" -o ./KIT_mesh/ShowerGel.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Margarine/meshes.zip" -o ./KIT_mesh/Margarine.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/MilkRice/meshes.zip" -o ./KIT_mesh/MilkRice.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Patches/meshes.zip" -o ./KIT_mesh/Patches.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/PotatoeDumplings/meshes.zip" -o ./KIT_mesh/PotatoeDumplings.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CoughDropsLemon/meshes.zip" -o ./KIT_mesh/CoughDropsLemon.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CoughDropsHoney/meshes.zip" -o ./KIT_mesh/CoughDropsHoney.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CoughDropsBerries/meshes.zip" -o ./KIT_mesh/CoughDropsBerries.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/FruitBars/meshes.zip" -o ./KIT_mesh/FruitBars.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/PatchesSensitive/meshes.zip" -o ./KIT_mesh/PatchesSensitive.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/SardinesCan/meshes.zip" -o ./KIT_mesh/SardinesCan.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/DropsOrange/meshes.zip" -o ./KIT_mesh/DropsOrange.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/DropsCherry/meshes.zip" -o ./KIT_mesh/DropsCherry.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/FizzyTablets/meshes.zip" -o ./KIT_mesh/FizzyTablets.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/FizzyTabletsCalcium/meshes.zip" -o ./KIT_mesh/FizzyTabletsCalcium.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/PotatoeSticks/meshes.zip" -o ./KIT_mesh/PotatoeSticks.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Wafflerolls/meshes.zip" -o ./KIT_mesh/Wafflerolls.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Shampoo/meshes.zip" -o ./KIT_mesh/Shampoo.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/HamburgerSauce/meshes.zip" -o ./KIT_mesh/HamburgerSauce.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/RuskWholemeal/meshes.zip" -o ./KIT_mesh/RuskWholemeal.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/NutCandy/meshes.zip" -o ./KIT_mesh/NutCandy.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/KoalaCandy/meshes.zip" -o ./KIT_mesh/KoalaCandy.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ChickenSoup/meshes.zip" -o ./KIT_mesh/ChickenSoup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/InstantTomatoSoup/meshes.zip" -o ./KIT_mesh/InstantTomatoSoup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/BroccoliSoup/meshes.zip" -o ./KIT_mesh/BroccoliSoup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CoffeeCookies/meshes.zip" -o ./KIT_mesh/CoffeeCookies.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/BakingSoda/meshes.zip" -o ./KIT_mesh/BakingSoda.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Sweetener/meshes.zip" -o ./KIT_mesh/Sweetener.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/BakingVanilla/meshes.zip" -o ./KIT_mesh/BakingVanilla.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ChocoIcing/meshes.zip" -o ./KIT_mesh/ChocoIcing.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CleaningCloths/meshes.zip" -o ./KIT_mesh/CleaningCloths.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/NutellaGo/meshes.zip" -o ./KIT_mesh/NutellaGo.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/StrawberryPorridge/meshes.zip" -o ./KIT_mesh/StrawberryPorridge.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/OrgFruitTea/meshes.zip" -o ./KIT_mesh/OrgFruitTea.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/OrgHerbTea/meshes.zip" -o ./KIT_mesh/OrgHerbTea.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/WhippedCream2/meshes.zip" -o ./KIT_mesh/WhippedCream2.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Marjoram/meshes.zip" -o ./KIT_mesh/Marjoram.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Curry/meshes.zip" -o ./KIT_mesh/Curry.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Paprika/meshes.zip" -o ./KIT_mesh/Paprika.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/TomatoHerbSauce/meshes.zip" -o ./KIT_mesh/TomatoHerbSauce.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ChocSticks/meshes.zip" -o ./KIT_mesh/ChocSticks.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ChocSticks2/meshes.zip" -o ./KIT_mesh/ChocSticks2.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Peanuts/meshes.zip" -o ./KIT_mesh/Peanuts.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Peanuts2/meshes.zip" -o ./KIT_mesh/Peanuts2.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/InstantSauce2/meshes.zip" -o ./KIT_mesh/InstantSauce2.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Peas/meshes.zip" -o ./KIT_mesh/Peas.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/HerbSalt/meshes.zip" -o ./KIT_mesh/HerbSalt.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/SoftCheese/meshes.zip" -o ./KIT_mesh/SoftCheese.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/BathDetergent/meshes.zip" -o ./KIT_mesh/BathDetergent.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ChocMarshmallows/meshes.zip" -o ./KIT_mesh/ChocMarshmallows.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CokePlasticLarge/meshes.zip" -o ./KIT_mesh/CokePlasticLarge.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CokePlasticSmall/meshes.zip" -o ./KIT_mesh/CokePlasticSmall.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/VitalisCereals/meshes.zip" -o ./KIT_mesh/VitalisCereals.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/SmacksCereals/meshes.zip" -o ./KIT_mesh/SmacksCereals.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Sprudelflasche/meshes.zip" -o ./KIT_mesh/Sprudelflasche.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Wineglass/meshes.zip" -o ./KIT_mesh/Wineglass.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Waterglass/meshes.zip" -o ./KIT_mesh/Waterglass.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/SmallGlass/meshes.zip" -o ./KIT_mesh/SmallGlass.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Glassbowl/meshes.zip" -o ./KIT_mesh/Glassbowl.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/WhiteCup/meshes.zip" -o ./KIT_mesh/WhiteCup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Pitcher/meshes.zip" -o ./KIT_mesh/Pitcher.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Sprayflask/meshes.zip" -o ./KIT_mesh/Sprayflask.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/InstantSauce/meshes.zip" -o ./KIT_mesh/InstantSauce.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/GreenCup/meshes.zip" -o ./KIT_mesh/GreenCup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/ToyCarYelloq/meshes.zip" -o ./KIT_mesh/ToyCarYelloq.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/FlowerCup/meshes.zip" -o ./KIT_mesh/FlowerCup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/MelforBottle/meshes.zip" -o ./KIT_mesh/MelforBottle.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CokePlasticSmallGrasp/meshes.zip" -o ./KIT_mesh/CokePlasticSmallGrasp.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/RedCup/meshes.zip" -o ./KIT_mesh/RedCup.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CatLying/meshes.zip" -o ./KIT_mesh/CatLying.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CatSitting/meshes.zip" -o ./KIT_mesh/CatSitting.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Clown/meshes.zip" -o ./KIT_mesh/Clown.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Dog/meshes.zip" -o ./KIT_mesh/Dog.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Dwarf/meshes.zip" -o ./KIT_mesh/Dwarf.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Fish/meshes.zip" -o ./KIT_mesh/Fish.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Heart1/meshes.zip" -o ./KIT_mesh/Heart1.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/LetterP/meshes.zip" -o ./KIT_mesh/LetterP.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Moon/meshes.zip" -o ./KIT_mesh/Moon.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Pony/meshes.zip" -o ./KIT_mesh/Pony.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Seal/meshes.zip" -o ./KIT_mesh/Seal.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Tortoise/meshes.zip" -o ./KIT_mesh/Tortoise.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/CoffeeBox/meshes.zip" -o ./KIT_mesh/CoffeeBox.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Cutter/meshes.zip" -o ./KIT_mesh/Cutter.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Brush/meshes.zip" -o ./KIT_mesh/Brush.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Flashlight/meshes.zip" -o ./KIT_mesh/Flashlight.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Phillips/meshes.zip" -o ./KIT_mesh/Phillips.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Slotted_Screwdriver/meshes.zip" -o ./KIT_mesh/Slotted_Screwdriver.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Wrench/meshes.zip" -o ./KIT_mesh/Wrench.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Spraybottle/meshes.zip" -o ./KIT_mesh/Spraybottle.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Stanley_Lever/meshes.zip" -o ./KIT_mesh/Stanley_Lever.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Stanley_Extension_Short/meshes.zip" -o ./KIT_mesh/Stanley_Extension_Short.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Stanley_Extension_Long/meshes.zip" -o ./KIT_mesh/Stanley_Extension_Long.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Stanley_Extension_Medium/meshes.zip" -o ./KIT_mesh/Stanley_Extension_Medium.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Stanley_Handle/meshes.zip" -o ./KIT_mesh/Stanley_Handle.zip 
curl "https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/Objects/Pliers/meshes.zip" -o ./KIT_mesh/Pliers.zip 