mv ./objects/OrangeMarmelade ./objects/191_OrangeMarmelade
mv ./objects/BlueSaltCube ./objects/192_BlueSaltCube
mv ./objects/YellowSaltCube ./objects/193_YellowSaltCube
mv ./objects/FruitTea ./objects/194_FruitTea
mv ./objects/GreenSaltCylinder ./objects/195_GreenSaltCylinder
mv ./objects/MashedPotatoes ./objects/196_MashedPotatoes
mv ./objects/YellowSaltCylinder ./objects/197_YellowSaltCylinder
mv ./objects/Rusk ./objects/198_Rusk
mv ./objects/Knaeckebrot ./objects/199_Knaeckebrot
mv ./objects/Amicelli ./objects/200_Amicelli
mv ./objects/HotPot ./objects/201_HotPot
mv ./objects/YellowSaltCube2 ./objects/202_YellowSaltCube2
mv ./objects/Sauerkraut ./objects/203_Sauerkraut
mv ./objects/LivioClassicOil ./objects/204_LivioClassicOil
mv ./objects/LivioSunflowerOil ./objects/205_LivioSunflowerOil
mv ./objects/DanishHam ./objects/206_DanishHam
mv ./objects/TomatoSoup ./objects/207_TomatoSoup
mv ./objects/SauerkrautSmall ./objects/208_SauerkrautSmall
mv ./objects/HeringTin ./objects/209_HeringTin
mv ./objects/RavioliLarge ./objects/210_RavioliLarge
mv ./objects/InstantSoup ./objects/211_InstantSoup
mv ./objects/Toothpaste ./objects/212_Toothpaste
mv ./objects/HotPot2 ./objects/213_HotPot2
mv ./objects/KnaeckebrotRye ./objects/214_KnaeckebrotRye
mv ./objects/CeylonTea ./objects/215_CeylonTea
mv ./objects/Rice ./objects/216_Rice
mv ./objects/FennelTea ./objects/217_FennelTea
mv ./objects/MuesliBars ./objects/218_MuesliBars
mv ./objects/Deodorant ./objects/219_Deodorant
mv ./objects/HygieneSpray ./objects/220_HygieneSpray
mv ./objects/PowderedSugar ./objects/221_PowderedSugar
mv ./objects/CondensedMilk ./objects/222_CondensedMilk
mv ./objects/SoftCakeOrange ./objects/223_SoftCakeOrange
mv ./objects/CoffeeFilters ./objects/224_CoffeeFilters
mv ./objects/PineappleSlices ./objects/225_PineappleSlices
mv ./objects/FruitDrink ./objects/226_FruitDrink
mv ./objects/InstantIceCoffee ./objects/227_InstantIceCoffee
mv ./objects/ChoppedTomatoes ./objects/228_ChoppedTomatoes
mv ./objects/MilkDrinkVanilla ./objects/229_MilkDrinkVanilla
mv ./objects/WhippedCream ./objects/230_WhippedCream
mv ./objects/PotatoeStarch ./objects/231_PotatoeStarch
mv ./objects/InstantDumplings ./objects/232_InstantDumplings
mv ./objects/ChocolateBars ./objects/233_ChocolateBars
mv ./objects/JamSugar ./objects/234_JamSugar
mv ./objects/YellowSaltCylinderSmall ./objects/235_YellowSaltCylinderSmall
mv ./objects/InstantMousse ./objects/236_InstantMousse
mv ./objects/TomatoSauce ./objects/237_TomatoSauce
mv ./objects/PowderedSugarMill ./objects/238_PowderedSugarMill
mv ./objects/SauceThickener ./objects/239_SauceThickener
mv ./objects/CoffeeFilters2 ./objects/240_CoffeeFilters2
mv ./objects/ShowerGel ./objects/241_ShowerGel
mv ./objects/Margarine ./objects/242_Margarine
mv ./objects/MilkRice ./objects/243_MilkRice
mv ./objects/Patches ./objects/244_Patches
mv ./objects/PotatoeDumplings ./objects/245_PotatoeDumplings
mv ./objects/CoughDropsLemon ./objects/246_CoughDropsLemon
mv ./objects/CoughDropsHoney ./objects/247_CoughDropsHoney
mv ./objects/CoughDropsBerries ./objects/248_CoughDropsBerries
mv ./objects/FruitBars ./objects/249_FruitBars
mv ./objects/PatchesSensitive ./objects/250_PatchesSensitive
mv ./objects/SardinesCan ./objects/251_SardinesCan
mv ./objects/DropsOrange ./objects/252_DropsOrange
mv ./objects/DropsCherry ./objects/253_DropsCherry
mv ./objects/FizzyTablets ./objects/254_FizzyTablets
mv ./objects/FizzyTabletsCalcium ./objects/255_FizzyTabletsCalcium
mv ./objects/PotatoeSticks ./objects/256_PotatoeSticks
mv ./objects/Wafflerolls ./objects/257_Wafflerolls
mv ./objects/Shampoo ./objects/258_Shampoo
mv ./objects/HamburgerSauce ./objects/259_HamburgerSauce
mv ./objects/RuskWholemeal ./objects/260_RuskWholemeal
mv ./objects/NutCandy ./objects/261_NutCandy
mv ./objects/KoalaCandy ./objects/262_KoalaCandy
mv ./objects/ChickenSoup ./objects/263_ChickenSoup
mv ./objects/InstantTomatoSoup ./objects/264_InstantTomatoSoup
mv ./objects/BroccoliSoup ./objects/265_BroccoliSoup
mv ./objects/CoffeeCookies ./objects/266_CoffeeCookies
mv ./objects/BakingSoda ./objects/267_BakingSoda
mv ./objects/Sweetener ./objects/268_Sweetener
mv ./objects/BakingVanilla ./objects/269_BakingVanilla
mv ./objects/ChocoIcing ./objects/270_ChocoIcing
mv ./objects/CleaningCloths ./objects/271_CleaningCloths
mv ./objects/NutellaGo ./objects/272_NutellaGo
mv ./objects/StrawberryPorridge ./objects/273_StrawberryPorridge
mv ./objects/OrgFruitTea ./objects/274_OrgFruitTea
mv ./objects/OrgHerbTea ./objects/275_OrgHerbTea
mv ./objects/WhippedCream2 ./objects/276_WhippedCream2
mv ./objects/Marjoram ./objects/277_Marjoram
mv ./objects/Curry ./objects/278_Curry
mv ./objects/Paprika ./objects/279_Paprika
mv ./objects/TomatoHerbSauce ./objects/280_TomatoHerbSauce
mv ./objects/ChocSticks ./objects/281_ChocSticks
mv ./objects/ChocSticks2 ./objects/282_ChocSticks2
mv ./objects/Peanuts ./objects/283_Peanuts
mv ./objects/Peanuts2 ./objects/284_Peanuts2
mv ./objects/InstantSauce2 ./objects/285_InstantSauce2
mv ./objects/Peas ./objects/286_Peas
mv ./objects/HerbSalt ./objects/287_HerbSalt
mv ./objects/SoftCheese ./objects/288_SoftCheese
mv ./objects/BathDetergent ./objects/289_BathDetergent
mv ./objects/ChocMarshmallows ./objects/290_ChocMarshmallows
mv ./objects/CokePlasticLarge ./objects/291_CokePlasticLarge
mv ./objects/CokePlasticSmall ./objects/292_CokePlasticSmall
mv ./objects/VitalisCereals ./objects/293_VitalisCereals
mv ./objects/SmacksCereals ./objects/294_SmacksCereals
mv ./objects/Sprudelflasche ./objects/295_Sprudelflasche
mv ./objects/Wineglass ./objects/296_Wineglass
mv ./objects/Waterglass ./objects/297_Waterglass
mv ./objects/SmallGlass ./objects/298_SmallGlass
mv ./objects/Glassbowl ./objects/299_Glassbowl
mv ./objects/WhiteCup ./objects/300_WhiteCup
mv ./objects/Pitcher ./objects/301_Pitcher
mv ./objects/Sprayflask ./objects/302_Sprayflask
mv ./objects/InstantSauce ./objects/303_InstantSauce
mv ./objects/GreenCup ./objects/304_GreenCup
mv ./objects/ToyCarYelloq ./objects/305_ToyCarYelloq
mv ./objects/FlowerCup ./objects/306_FlowerCup
mv ./objects/MelforBottle ./objects/307_MelforBottle
mv ./objects/CokePlasticSmallGrasp ./objects/308_CokePlasticSmallGrasp
mv ./objects/RedCup ./objects/309_RedCup
mv ./objects/CatLying ./objects/310_CatLying
mv ./objects/CatSitting ./objects/311_CatSitting
mv ./objects/Clown ./objects/312_Clown
mv ./objects/Dog ./objects/313_Dog
mv ./objects/Dwarf ./objects/314_Dwarf
mv ./objects/Fish ./objects/315_Fish
mv ./objects/Heart1 ./objects/316_Heart1
mv ./objects/LetterP ./objects/317_LetterP
mv ./objects/Moon ./objects/318_Moon
mv ./objects/Pony ./objects/319_Pony
mv ./objects/Seal ./objects/320_Seal
mv ./objects/Tortoise ./objects/321_Tortoise
mv ./objects/CoffeeBox ./objects/322_CoffeeBox
mv ./objects/Cutter ./objects/323_Cutter
mv ./objects/Brush ./objects/324_Brush
mv ./objects/Flashlight ./objects/325_Flashlight
mv ./objects/Phillips ./objects/326_Phillips
mv ./objects/Slotted_Screwdriver ./objects/327_Slotted_Screwdriver
mv ./objects/Wrench ./objects/328_Wrench
mv ./objects/Spraybottle ./objects/329_Spraybottle
mv ./objects/Stanley_Lever ./objects/330_Stanley_Lever
mv ./objects/Stanley_Extension_Short ./objects/331_Stanley_Extension_Short
mv ./objects/Stanley_Extension_Long ./objects/332_Stanley_Extension_Long
mv ./objects/Stanley_Extension_Medium ./objects/333_Stanley_Extension_Medium
mv ./objects/Stanley_Handle ./objects/334_Stanley_Handle
mv ./objects/Pliers ./objects/335_Pliers