mkdir ./KIT_mesh/OrangeMarmelade
mkdir ./KIT_mesh/BlueSaltCube
mkdir ./KIT_mesh/YellowSaltCube
mkdir ./KIT_mesh/FruitTea
mkdir ./KIT_mesh/GreenSaltCylinder
mkdir ./KIT_mesh/MashedPotatoes
mkdir ./KIT_mesh/YellowSaltCylinder
mkdir ./KIT_mesh/Rusk
mkdir ./KIT_mesh/Knaeckebrot
mkdir ./KIT_mesh/Amicelli
mkdir ./KIT_mesh/HotPot
mkdir ./KIT_mesh/YellowSaltCube2
mkdir ./KIT_mesh/Sauerkraut
mkdir ./KIT_mesh/LivioClassicOil
mkdir ./KIT_mesh/LivioSunflowerOil
mkdir ./KIT_mesh/DanishHam
mkdir ./KIT_mesh/TomatoSoup
mkdir ./KIT_mesh/SauerkrautSmall
mkdir ./KIT_mesh/HeringTin
mkdir ./KIT_mesh/RavioliLarge
mkdir ./KIT_mesh/InstantSoup
mkdir ./KIT_mesh/Toothpaste
mkdir ./KIT_mesh/HotPot2
mkdir ./KIT_mesh/KnaeckebrotRye
mkdir ./KIT_mesh/CeylonTea
mkdir ./KIT_mesh/Rice
mkdir ./KIT_mesh/FennelTea
mkdir ./KIT_mesh/MuesliBars
mkdir ./KIT_mesh/Deodorant
mkdir ./KIT_mesh/HygieneSpray
mkdir ./KIT_mesh/PowderedSugar
mkdir ./KIT_mesh/CondensedMilk
mkdir ./KIT_mesh/SoftCakeOrange
mkdir ./KIT_mesh/CoffeeFilters
mkdir ./KIT_mesh/PineappleSlices
mkdir ./KIT_mesh/FruitDrink
mkdir ./KIT_mesh/InstantIceCoffee
mkdir ./KIT_mesh/ChoppedTomatoes
mkdir ./KIT_mesh/MilkDrinkVanilla
mkdir ./KIT_mesh/WhippedCream
mkdir ./KIT_mesh/PotatoeStarch
mkdir ./KIT_mesh/InstantDumplings
mkdir ./KIT_mesh/ChocolateBars
mkdir ./KIT_mesh/JamSugar
mkdir ./KIT_mesh/YellowSaltCylinderSmall
mkdir ./KIT_mesh/InstantMousse
mkdir ./KIT_mesh/TomatoSauce
mkdir ./KIT_mesh/PowderedSugarMill
mkdir ./KIT_mesh/SauceThickener
mkdir ./KIT_mesh/CoffeeFilters2
mkdir ./KIT_mesh/ShowerGel
mkdir ./KIT_mesh/Margarine
mkdir ./KIT_mesh/MilkRice
mkdir ./KIT_mesh/Patches
mkdir ./KIT_mesh/PotatoeDumplings
mkdir ./KIT_mesh/CoughDropsLemon
mkdir ./KIT_mesh/CoughDropsHoney
mkdir ./KIT_mesh/CoughDropsBerries
mkdir ./KIT_mesh/FruitBars
mkdir ./KIT_mesh/PatchesSensitive
mkdir ./KIT_mesh/SardinesCan
mkdir ./KIT_mesh/DropsOrange
mkdir ./KIT_mesh/DropsCherry
mkdir ./KIT_mesh/FizzyTablets
mkdir ./KIT_mesh/FizzyTabletsCalcium
mkdir ./KIT_mesh/PotatoeSticks
mkdir ./KIT_mesh/Wafflerolls
mkdir ./KIT_mesh/Shampoo
mkdir ./KIT_mesh/HamburgerSauce
mkdir ./KIT_mesh/RuskWholemeal
mkdir ./KIT_mesh/NutCandy
mkdir ./KIT_mesh/KoalaCandy
mkdir ./KIT_mesh/ChickenSoup
mkdir ./KIT_mesh/InstantTomatoSoup
mkdir ./KIT_mesh/BroccoliSoup
mkdir ./KIT_mesh/CoffeeCookies
mkdir ./KIT_mesh/BakingSoda
mkdir ./KIT_mesh/Sweetener
mkdir ./KIT_mesh/BakingVanilla
mkdir ./KIT_mesh/ChocoIcing
mkdir ./KIT_mesh/CleaningCloths
mkdir ./KIT_mesh/NutellaGo
mkdir ./KIT_mesh/StrawberryPorridge
mkdir ./KIT_mesh/OrgFruitTea
mkdir ./KIT_mesh/OrgHerbTea
mkdir ./KIT_mesh/WhippedCream2
mkdir ./KIT_mesh/Marjoram
mkdir ./KIT_mesh/Curry
mkdir ./KIT_mesh/Paprika
mkdir ./KIT_mesh/TomatoHerbSauce
mkdir ./KIT_mesh/ChocSticks
mkdir ./KIT_mesh/ChocSticks2
mkdir ./KIT_mesh/Peanuts
mkdir ./KIT_mesh/Peanuts2
mkdir ./KIT_mesh/InstantSauce2
mkdir ./KIT_mesh/Peas
mkdir ./KIT_mesh/HerbSalt
mkdir ./KIT_mesh/SoftCheese
mkdir ./KIT_mesh/BathDetergent
mkdir ./KIT_mesh/ChocMarshmallows
mkdir ./KIT_mesh/CokePlasticLarge
mkdir ./KIT_mesh/CokePlasticSmall
mkdir ./KIT_mesh/VitalisCereals
mkdir ./KIT_mesh/SmacksCereals
mkdir ./KIT_mesh/Sprudelflasche
mkdir ./KIT_mesh/Wineglass
mkdir ./KIT_mesh/Waterglass
mkdir ./KIT_mesh/SmallGlass
mkdir ./KIT_mesh/Glassbowl
mkdir ./KIT_mesh/WhiteCup
mkdir ./KIT_mesh/Pitcher
mkdir ./KIT_mesh/Sprayflask
mkdir ./KIT_mesh/InstantSauce
mkdir ./KIT_mesh/GreenCup
mkdir ./KIT_mesh/ToyCarYelloq
mkdir ./KIT_mesh/FlowerCup
mkdir ./KIT_mesh/MelforBottle
mkdir ./KIT_mesh/CokePlasticSmallGrasp
mkdir ./KIT_mesh/RedCup
mkdir ./KIT_mesh/CatLying
mkdir ./KIT_mesh/CatSitting
mkdir ./KIT_mesh/Clown
mkdir ./KIT_mesh/Dog
mkdir ./KIT_mesh/Dwarf
mkdir ./KIT_mesh/Fish
mkdir ./KIT_mesh/Heart1
mkdir ./KIT_mesh/LetterP
mkdir ./KIT_mesh/Moon
mkdir ./KIT_mesh/Pony
mkdir ./KIT_mesh/Seal
mkdir ./KIT_mesh/Tortoise
mkdir ./KIT_mesh/CoffeeBox
mkdir ./KIT_mesh/Cutter
mkdir ./KIT_mesh/Brush
mkdir ./KIT_mesh/Flashlight
mkdir ./KIT_mesh/Phillips
mkdir ./KIT_mesh/Slotted_Screwdriver
mkdir ./KIT_mesh/Wrench
mkdir ./KIT_mesh/Spraybottle
mkdir ./KIT_mesh/Stanley_Lever
mkdir ./KIT_mesh/Stanley_Extension_Short
mkdir ./KIT_mesh/Stanley_Extension_Long
mkdir ./KIT_mesh/Stanley_Extension_Medium
mkdir ./KIT_mesh/Stanley_Handle
mkdir ./KIT_mesh/Pliers